from django.shortcuts import render

# Create your views here.

def baabtra_home(request):
    return render(request,'baabtra/home.html')
def baabtra1(request):
    return render(request,'baabtra/baabtra1.html')
def baabtra2(request):
    return render(request,'baabtra/baabtra2.html')
def baabtra3(request):
    return render(request,'baabtra/baabtra3.html')
def largest2(request):
    return render(request,'baabtra/largest2.html')
def largest3(request):
    return render(request,'baabtra/largest3.html')
def sumnumber(request):
    return render(request,'baabtra/sumnumber.html')
def reverse(request):
    return render(request,'baabtra/reverse.html')
def palindrome(request):
    return render(request,'baabtra/palindrome.html')
def largest_digit(request):
    return render(request,'baabtra/largest_digit.html')
def numberof_digit(request):
    return render(request,'baabtra/numberof_digit.html')
def pattern1(request):
    return render(request,'baabtra/pattern1.html')
def pattern2(request):
    return render(request,'baabtra/pattern2.html')
def pattern3(request):
    return render(request,'baabtra/pattern3.html')
def pattern4(request):
    return render(request,'baabtra/pattern4.html')
def pattern5(request):
    return render(request,'baabtra/pattern5.html')
def pattern6(request):
    return render(request,'baabtra/pattern6.html')
def programme(request):
    return render(request,'baabtra/programme.html')
def array(request):
    return render(request,'baabtra/array.html')
def dom(request):
    return render(request,'baabtra/dom.html')
def dom2(request):
    return render(request,'baabtra/dom2.html')
def dom3(request):
    return render(request,'baabtra/dom3.html')
def password(request):
    return render(request,'baabtra/password.html')
def calculator(request):
    return render(request,'baabtra/calculator.html')
def jquery(request):
    return render(request,'baabtra/jquery.html')
def product(request):
    return render(request,'baabtra/product.html')
def addproduct(request):
    return render(request,'baabtra/addproduct.html')
def viewproduct(request):
    return render(request,'baabtra/viewproduct.html')
def validation(request):
    return render(request,'baabtra/validation.html')    
